<a href="https://colab.research.google.com/github/matin-karimpour/Covid19-Xray/blob/main/Tensorflow_Vs_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# TensorFlow

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
x = np.arange(10)
y = x*2 -1

In [ ]:
y

array([-1,  1,  3,  5,  7,  9, 11, 13, 15, 17])

In [ ]:
model = tf.keras.models.Sequential([tf.keras.layers.Dense(1, input_shape=[1])])

In [ ]:
model.compile(optimizer="sgd",
              loss="mean_squared_error",)

In [ ]:
model.fit(x, y, epochs=1000)

Epoch 1/1000
1/1 [==============================] - 0s 318ms/step - loss: 201.4744
Epoch 2/1000
1/1 [==============================] - 0s 13ms/step - loss: 35.2789
Epoch 3/1000
1/1 [==============================] - 0s 15ms/step - loss: 6.5613
Epoch 4/1000
1/1 [==============================] - 0s 13ms/step - loss: 1.5947
Epoch 5/1000
1/1 [==============================] - 0s 11ms/step - loss: 0.7314
Epoch 6/1000
1/1 [==============================] - 0s 16ms/step - loss: 0.5772
Epoch 7/1000
1/1 [==============================] - 0s 11ms/step - loss: 0.5454
Epoch 8/1000
1/1 [==============================] - 0s 11ms/step - loss: 0.5349
Epoch 9/1000
1/1 [==============================] - 0s 11ms/step - loss: 0.5281
Epoch 10/1000
1/1 [==============================] - 0s 9ms/step - loss: 0.5221
Epoch 11/1000
1/1 [==============================] - 0s 11ms/step - loss: 0.5162
Epoch 12/1000
1/1 [==============================] - 0s 15ms/step - loss: 0.5103
Epoch 13/1000
1/1 [===============

In [ ]:
model.predict([[120]])

1/1 [==============================] - 0s 44ms/step


array([[238.91104]], dtype=float32)

In [ ]:
120*2 -1

239

# PyTorch

In [4]:
import torch
from torch import nn
from torch.utils.data import DataLoader, Dataset

In [6]:
device = ("cuda" if torch.cuda.is_available() else "cpu")
device

In [25]:
class SampleDataset(Dataset):
  def __init__(self, x, y):
    self.x = torch.tensor(x, dtype=torch.float32, device=device)
    self.y = torch.tensor(y, dtype=torch.float32, device=device)

  def __len__(self):
    return len(self.y)

  def __getitem__(self, idx):
    y = self.y[idx]
    x = self.x[idx]
    return x, y

In [26]:
train_dataset = SampleDataset(x, y)
train_dataloader = DataLoader(train_dataset, )

In [27]:
class NeuralNetwork(nn.Module):
    def __init__(self):
        super().__init__()
        self.layer1 = nn.Linear(1, 1)

    def forward(self, x):
        output = self.layer1(x)
        return output

model = NeuralNetwork().to(device)
print(model)

NeuralNetwork(
  (layer1): Linear(in_features=1, out_features=1, bias=True)
)


In [28]:
loss_fn = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=1e-2)

In [29]:
def train(dataloader, model, loss_fn, optimizer):
    size = len(dataloader.dataset)
    model.train()
    for batch, (X, y) in enumerate(dataloader):
        X, y = X.to(device), y.to(device)

        # Compute prediction error
        pred = model(X)
        loss = loss_fn(pred, y)

        # Backpropagation
        loss.backward()
        optimizer.step()
        optimizer.zero_grad()

        if batch % 100 == 0:
            loss, current = loss.item(), (batch + 1) * len(X)
            print(f"loss: {loss:>7f}  [{current:>5d}/{size:>5d}]")

In [30]:
epochs = 1000
for t in range(epochs):
    print(f"Epoch {t+1}\n-------------------------------")
    train(train_dataloader, model, loss_fn, optimizer)
print("Done!")

Epoch 1
-------------------------------
loss: 2.939630  [    1/   10]
Epoch 2
-------------------------------
loss: 4.291993  [    1/   10]
Epoch 3
-------------------------------
loss: 3.859360  [    1/   10]
Epoch 4
-------------------------------
loss: 3.470336  [    1/   10]
Epoch 5
-------------------------------
loss: 3.120527  [    1/   10]
Epoch 6
-------------------------------
loss: 2.805977  [    1/   10]
Epoch 7
-------------------------------
loss: 2.523134  [    1/   10]
Epoch 8
-------------------------------
loss: 2.268802  [    1/   10]
Epoch 9
-------------------------------
loss: 2.040107  [    1/   10]
Epoch 10
-------------------------------
loss: 1.834464  [    1/   10]
Epoch 11
-------------------------------
loss: 1.649550  [    1/   10]
Epoch 12
-------------------------------
loss: 1.483275  [    1/   10]
Epoch 13
-------------------------------
loss: 1.333761  [    1/   10]
Epoch 14
-------------------------------
loss: 1.199318  [    1/   10]
Epoch 15
------

In [33]:
model(torch.tensor([120], dtype=torch.float32))

tensor([239.0000], grad_fn=<ViewBackward0>)